### PR TITLE
Conv1d Support

### PR DESCRIPTION
**Pull request by ryendu**
Heyo @palle-k ! I've started this pull request even though I'm in the middle of, and no where close to being done with adding 1d convs... I'm just a bit stuck on the 1d equivalent for im2col and col2im (if that even exists). I don't want to change the code you wrote for im2col / col2im too much to make it 1d, however I'm having trouble understanding the code you wrote for im2col and col2im... Could you give me some guidance on what exactly everything is doing for im2col and col2im in the file "Sources/DL4S/Engine/CPU/Numeric/CPUGeneric.swift" please? Also, I apolagise if I don't know the name of the 1d equivilent of im2col, i just call it im2col1d lol.

### CODE REVIEW

**Comment by ryendu** [comment]
as of rn, I've basically tried just removing the y component from im2col and put that in im2col1d, but the convolution resulting from the test that uses this contains a bunch of zeros, and a few very very large numbers, and is just odd in general. Somethings just not right.

**Comment by palle-k** [comment]
Hey, [here's an explanation of im2col](https://www.programmersought.com/article/8156527203/). 

im2col works by copying patches from the source tensor into the destination tensor, such that the convolution operation (multiplying every element in the patch with the kernel and then summing them up) is expressed as a matrix multiplication.

The outermost loop (`for k in ...`) goes over each element in the convolution kernel, the body of this loop then collects all the elements that should be multiplied with this element of the kernel. Within the loops, the code checks, whether elements should be copied from the source tensor or whether they are in a region that is outside of the source tensor, so that they should be zero padded. 

With some clever reshaping, I think it may be possible to completely avoid having to write a new im2col implementation for the 1D case by expressing the 1D convolution as some reshaping followed by a 2D convolution with a X*1 kernel.

**Comment by ryendu** [comment]
Thanks for the suggestions and tips, I'll start working on it : ).

**Comment by ryendu** [comment]
Heyo @palle-k 👋, sorry to bother you again, but I ran into some problems when using Tensor's utility function, **padded**. As you can see in line 165 of ```Tensor>Operations>Conv.swift```, I am trying to pad the input tensor in the conv1d function instead of letting conv2d pad it because conv2d would pad both vertically and horizontally. This code however throws a precondition error when ran with ```testConv1d``` (line 135 of ```ConvTests.swift```) on line 60 of```Memory Management > Allocator.swift```. the line reads: ```precondition(ptr.count >= count, "Out of bounds access")``` and the error thrown is: ```Thread 1: Precondition failed: Out of bounds access```. If I comment out line 60 and 61 of ```Allocator.swift``` to override this message, the padding kind of works... Given an input of ```[[[0.526, 0.921, 0.468, 0.089, 0.167, 0.374, 0.040, 0.255, 0.898]],
 [[0.227, 0.688, 0.868, 0.065, 0.706, 0.996, 0.518, 0.037, 0.193]]]```,this input and a padding of 1 run through line 165 of ```Conv.swift``` returns ```[[[0.000, 0.526, 0.921, 0.468, 0.089, 0.167, 0.374, 0.040, 0.255, 0.898, 0.000]],
 [[0.000, 0.868, 0.065, 0.706, 0.996, 0.518, 0.037, 0.193, 0.000, 0.000, 0.000]]]```, and as you can see, its half correct. the first half is padded correctly, however the second half is a bit off. Could this possibly be a bug, or am I doing something horribly wrong 😬.

**Comment by palle-k** [comment]
Hey, thanks for reporting this issue to me. I was able to reproduce this issue and I've pushed a fix :)

**Comment by ryendu** [comment]
Heyo, thanks for the fix quick to the padding issue, I've now finished up adding the new features. Heres a list of the changes I made: Added Conv1d, TransposedConv1d, AdaptiveMaxPool1d, AdaptiveAvgPool1d, AvgPool1d, and MaxPool1d. Along with that, updated documentation for added features and moved the navigation side bar into its own html file to avoid the hassle of copying and pasting the code for the nav bar 100+ times. Thank you so much for your help along the way! This PR is finally ready for review 😁!

**Comment by palle-k** [comment]
Hey, sorry to keep you waiting. 

Note that the whole documentation is automatically generated with [Jazzy](https://github.com/realm/jazzy), so any changes to the output HTML will get overwritten the next time the docs are generated. 

To regenerate the documentation, you can install Jazzy with `sudo gem install jazzy`. Then you can regenerate the documentation by running

    jazzy -c --output docs/ --config .jazzy.json

in the root folder of this repository.

Any changes to how the documentation is generated must be done by editing the .jazzy.json file.

**Comment by ryendu** [comment]
Hi, I have made the required changes to the `.jazzy.json` file, but could you help me generate the documentation please? After many attempts, I tried and failed to get jazzy to work on my M1 Mac.

**Pull request merged**
